version: "3.8"
services:
  react-app:
    build: .
    container_name: my-don-container
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
