<<<<<<< HEAD
version: "3.8"

services:
  react-app:
    build: .
    container_name: my-don-container
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
=======
version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
>>>>>>> 4db4230b482ffcaacf02fcbb7bf3ed212e762956
